name: Selenium UI Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.112' # Adjust if needed

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --no-restore --configuration Release

      - name: Start the MVC app
        run: dotnet run --project 7071Group/7071Group.csproj & # Ensure correct path
        env:
          ASPNETCORE_URLS: http://localhost:5000

      - name: Run Selenium UI Tests
        run: dotnet test --filter FullyQualifiedName~Tests.ClientViewTests

      - name: Upload test results (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-test-results
          path: TestResults
